"""changed homework table name

Revision ID: 7d57d94ecee6
Revises: c28e19ba2abd
Create Date: 2024-12-20 09:11:45.113233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d57d94ecee6'
down_revision: Union[str, None] = 'c28e19ba2abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homeworktable',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('classno', sa.Integer(), nullable=False),
    sa.Column('classsection', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('homeworkdate', sa.Date(), nullable=False),
    sa.Column('subsections', sa.JSON(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('homework2table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework2table',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('classno', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('classsection', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('homeworkdate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('subsections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='homework2table_pkey1')
    )
    op.drop_table('homeworktable')
    # ### end Alembic commands ###
