"""created feedback table

Revision ID: 868db63a7e34
Revises: c2a8c91ed5c9
Create Date: 2024-12-20 20:50:03.626948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '868db63a7e34'
down_revision: Union[str, None] = 'c2a8c91ed5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacktable',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('studentname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parentname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parentmobilenumber', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classno', sa.Integer(), nullable=False),
    sa.Column('classsection', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feedbackdate', sa.Date(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedbackdescription', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacktable')
    # ### end Alembic commands ###
