"""created complaint table

Revision ID: 8a84cfd9ea0e
Revises: 7d57d94ecee6
Create Date: 2024-12-20 20:17:42.586770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a84cfd9ea0e'
down_revision: Union[str, None] = '7d57d94ecee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaintable',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('studentname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parentname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parentmobilenumber', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classno', sa.Integer(), nullable=False),
    sa.Column('classsection', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('complaindate', sa.Date(), nullable=False),
    sa.Column('complaintdescription', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggestion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaintable')
    # ### end Alembic commands ###
